/*
Copyright 2023 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	networkingv1beta1 "istio.io/client-go/pkg/apis/networking/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// WorkloadGroupLister helps list WorkloadGroups.
// All objects returned here must be treated as read-only.
type WorkloadGroupLister interface {
	// List lists all WorkloadGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1beta1.WorkloadGroup, err error)
	// WorkloadGroups returns an object that can list and get WorkloadGroups.
	WorkloadGroups(namespace string) WorkloadGroupNamespaceLister
	WorkloadGroupListerExpansion
}

// workloadGroupLister implements the WorkloadGroupLister interface.
type workloadGroupLister struct {
	listers.ResourceIndexer[*networkingv1beta1.WorkloadGroup]
}

// NewWorkloadGroupLister returns a new WorkloadGroupLister.
func NewWorkloadGroupLister(indexer cache.Indexer) WorkloadGroupLister {
	return &workloadGroupLister{listers.New[*networkingv1beta1.WorkloadGroup](indexer, networkingv1beta1.Resource("workloadgroup"))}
}

// WorkloadGroups returns an object that can list and get WorkloadGroups.
func (s *workloadGroupLister) WorkloadGroups(namespace string) WorkloadGroupNamespaceLister {
	return workloadGroupNamespaceLister{listers.NewNamespaced[*networkingv1beta1.WorkloadGroup](s.ResourceIndexer, namespace)}
}

// WorkloadGroupNamespaceLister helps list and get WorkloadGroups.
// All objects returned here must be treated as read-only.
type WorkloadGroupNamespaceLister interface {
	// List lists all WorkloadGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1beta1.WorkloadGroup, err error)
	// Get retrieves the WorkloadGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkingv1beta1.WorkloadGroup, error)
	WorkloadGroupNamespaceListerExpansion
}

// workloadGroupNamespaceLister implements the WorkloadGroupNamespaceLister
// interface.
type workloadGroupNamespaceLister struct {
	listers.ResourceIndexer[*networkingv1beta1.WorkloadGroup]
}
